# Generated by Django 4.1.3 on 2022-12-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('purchaser', models.CharField(max_length=64)),
                ('description', models.TextField(default='description')),
            ],
        ),
    ]
